In [85]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

# Use the kagglehub client library to attach Kaggle resources like competitions, datasets, and models to your session
# Learn more about kagglehub: https://github.com/Kaggle/kagglehub/blob/main/README.md

import kagglehub

# Download latest version
path = kagglehub.competition_download('spaceship-titanic')

print("Path to competition files:", path)

/kaggle/input/competitions/spaceship-titanic/sample_submission.csv
/kaggle/input/competitions/spaceship-titanic/train.csv
/kaggle/input/competitions/spaceship-titanic/test.csv
Path to competition files: /kaggle/input/competitions/spaceship-titanic

In [86]:
import matplotlib.pyplot as plt
import seaborn as sns

In [87]:
train_data= pd.read_csv("/kaggle/input/competitions/spaceship-titanic/train.csv")
train_data

,PassengerId,HomePlanet,CryoSleep,Cabin,Destination,Age,VIP,RoomService,FoodCourt,ShoppingMall,Spa,VRDeck,Name,Transported
0,0001_01,Europa,False,B/0/P,TRAPPIST-1e,39.0,False,0.0,0.0,0.0,0.0,0.0,Maham Ofracculy,False
1,0002_01,Earth,False,F/0/S,TRAPPIST-1e,24.0,False,109.0,9.0,25.0,549.0,44.0,Juanna Vines,True
2,0003_01,Europa,False,A/0/S,TRAPPIST-1e,58.0,True,43.0,3576.0,0.0,6715.0,49.0,Altark Susent,False
3,0003_02,Europa,False,A/0/S,TRAPPIST-1e,33.0,False,0.0,1283.0,371.0,3329.0,193.0,Solam Susent,False
4,0004_01,Earth,False,F/1/S,TRAPPIST-1e,16.0,False,303.0,70.0,151.0,565.0,2.0,Willy Santantines,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8688,9276_01,Europa,False,A/98/P,55 Cancri e,41.0,True,0.0,6819.0,0.0,1643.0,74.0,Gravior Noxnuther,False
8689,9278_01,Earth,True,G/1499/S,PSO J318.5-22,18.0,False,0.0,0.0,0.0,0.0,0.0,Kurta Mondalley,False
8690,9279_01,Earth,False,G/1500/S,TRAPPIST-1e,26.0,False,0.0,0.0,1872.0,1.0,0.0,Fayey Connon,True
8691,9280_01,Europa,False,E/608/S,55 Cancri e,32.0,False,0.0,1049.0,0.0,353.0,3235.0,Celeon Hontichre,False
8692,9280_02,Europa,False,E/608/S,TRAPPIST-1e,44.0,False,126.0,4688.0,0.0,0.0,12.0,Propsh Hontichre,True

In [88]:
test_data= pd.read_csv("/kaggle/input/competitions/spaceship-titanic/test.csv")
test_data

,PassengerId,HomePlanet,CryoSleep,Cabin,Destination,Age,VIP,RoomService,FoodCourt,ShoppingMall,Spa,VRDeck,Name
0,0013_01,Earth,True,G/3/S,TRAPPIST-1e,27.0,False,0.0,0.0,0.0,0.0,0.0,Nelly Carsoning
1,0018_01,Earth,False,F/4/S,TRAPPIST-1e,19.0,False,0.0,9.0,0.0,2823.0,0.0,Lerome Peckers
2,0019_01,Europa,True,C/0/S,55 Cancri e,31.0,False,0.0,0.0,0.0,0.0,0.0,Sabih Unhearfus
3,0021_01,Europa,False,C/1/S,TRAPPIST-1e,38.0,False,0.0,6652.0,0.0,181.0,585.0,Meratz Caltilter
4,0023_01,Earth,False,F/5/S,TRAPPIST-1e,20.0,False,10.0,0.0,635.0,0.0,0.0,Brence Harperez
...,...,...,...,...,...,...,...,...,...,...,...,...,...
4272,9266_02,Earth,True,G/1496/S,TRAPPIST-1e,34.0,False,0.0,0.0,0.0,0.0,0.0,Jeron Peter
4273,9269_01,Earth,False,NaN,TRAPPIST-1e,42.0,False,0.0,847.0,17.0,10.0,144.0,Matty Scheron
4274,9271_01,Mars,True,D/296/P,55 Cancri e,NaN,False,0.0,0.0,0.0,0.0,0.0,Jayrin Pore
4275,9273_01,Europa,False,D/297/P,NaN,NaN,False,0.0,2680.0,0.0,0.0,523.0,Kitakan Conale
4276,9277_01,Earth,True,G/1498/S,PSO J318.5-22,43.0,False,0.0,0.0,0.0,0.0,0.0,Lilace Leonzaley

In [89]:
train_data= train_data.drop(columns="PassengerId")
train_data= train_data.drop(columns="Name")
train_data.head()

,HomePlanet,CryoSleep,Cabin,Destination,Age,VIP,RoomService,FoodCourt,ShoppingMall,Spa,VRDeck,Transported
0,Europa,False,B/0/P,TRAPPIST-1e,39.0,False,0.0,0.0,0.0,0.0,0.0,False
1,Earth,False,F/0/S,TRAPPIST-1e,24.0,False,109.0,9.0,25.0,549.0,44.0,True
2,Europa,False,A/0/S,TRAPPIST-1e,58.0,True,43.0,3576.0,0.0,6715.0,49.0,False
3,Europa,False,A/0/S,TRAPPIST-1e,33.0,False,0.0,1283.0,371.0,3329.0,193.0,False
4,Earth,False,F/1/S,TRAPPIST-1e,16.0,False,303.0,70.0,151.0,565.0,2.0,True

In [90]:
test_data= test_data.drop(columns="PassengerId")
test_data= test_data.drop(columns="Name")
test_data.head()

,HomePlanet,CryoSleep,Cabin,Destination,Age,VIP,RoomService,FoodCourt,ShoppingMall,Spa,VRDeck
0,Earth,True,G/3/S,TRAPPIST-1e,27.0,False,0.0,0.0,0.0,0.0,0.0
1,Earth,False,F/4/S,TRAPPIST-1e,19.0,False,0.0,9.0,0.0,2823.0,0.0
2,Europa,True,C/0/S,55 Cancri e,31.0,False,0.0,0.0,0.0,0.0,0.0
3,Europa,False,C/1/S,TRAPPIST-1e,38.0,False,0.0,6652.0,0.0,181.0,585.0
4,Earth,False,F/5/S,TRAPPIST-1e,20.0,False,10.0,0.0,635.0,0.0,0.0

## Handling Missing Values in train and test data

In [91]:
train_data.isnull().mean()*100

HomePlanet      2.312205
CryoSleep       2.496261
Cabin           2.289198
Destination     2.093639
Age             2.059128
VIP             2.335212
RoomService     2.082135
FoodCourt       2.105142
ShoppingMall    2.392730
Spa             2.105142
VRDeck          2.162660
Transported     0.000000
dtype: float64

In [92]:
#For home planet
train_data['HomePlanet'] = train_data['HomePlanet'].fillna("U")
test_data['HomePlanet'] = test_data['HomePlanet'].fillna("U")

In [93]:
train_data["HomePlanet"].isnull().mean()*100

np.float64(0.0)

In [94]:
# For cabin
train_data['Cabin'] = train_data['Cabin'].fillna('U')
train_data['Deck'] = train_data['Cabin'].apply(lambda x: x[0])
train_data

,HomePlanet,CryoSleep,Cabin,Destination,Age,VIP,RoomService,FoodCourt,ShoppingMall,Spa,VRDeck,Transported,Deck
0,Europa,False,B/0/P,TRAPPIST-1e,39.0,False,0.0,0.0,0.0,0.0,0.0,False,B
1,Earth,False,F/0/S,TRAPPIST-1e,24.0,False,109.0,9.0,25.0,549.0,44.0,True,F
2,Europa,False,A/0/S,TRAPPIST-1e,58.0,True,43.0,3576.0,0.0,6715.0,49.0,False,A
3,Europa,False,A/0/S,TRAPPIST-1e,33.0,False,0.0,1283.0,371.0,3329.0,193.0,False,A
4,Earth,False,F/1/S,TRAPPIST-1e,16.0,False,303.0,70.0,151.0,565.0,2.0,True,F
...,...,...,...,...,...,...,...,...,...,...,...,...,...
8688,Europa,False,A/98/P,55 Cancri e,41.0,True,0.0,6819.0,0.0,1643.0,74.0,False,A
8689,Earth,True,G/1499/S,PSO J318.5-22,18.0,False,0.0,0.0,0.0,0.0,0.0,False,G
8690,Earth,False,G/1500/S,TRAPPIST-1e,26.0,False,0.0,0.0,1872.0,1.0,0.0,True,G
8691,Europa,False,E/608/S,55 Cancri e,32.0,False,0.0,1049.0,0.0,353.0,3235.0,False,E
8692,Europa,False,E/608/S,TRAPPIST-1e,44.0,False,126.0,4688.0,0.0,0.0,12.0,True,E

In [95]:
# Handling missing values in cyrosleep
amenities = ['RoomService', 'FoodCourt', 'ShoppingMall', 'Spa', 'VRDeck']
train_data['TotalShopping'] = train_data[amenities].sum(axis=1)
train_data.loc[train_data['CryoSleep'].isnull() & (train_data['TotalShopping'] > 0), 'CryoSleep'] = False
train_data.loc[train_data['CryoSleep'].isnull() & (train_data['TotalShopping'] == 0), 'CryoSleep'] = True

In [96]:
# Handling missing values in amenities
for col in amenities:
    train_data.loc[train_data['CryoSleep'] == True, col] = train_data[col].fillna(0)

In [97]:
# Handling missing values in destination
destination_mode = train_data['Destination'].mode()[0]
train_data['Destination'] = train_data['Destination'].fillna(destination_mode)

In [98]:
# Handling missing values in age by imputing median in NaN
from sklearn.impute import SimpleImputer
sim_imp= SimpleImputer(strategy="median")
train_data['Age']= pd.DataFrame(sim_imp.fit_transform(train_data[['Age']]))

In [99]:
#For missing values in VIP we can check whether they have used luxury amentites or not
train_data.loc[train_data['VIP'].isnull() & (train_data['TotalShopping'] > 0), 'VIP'] = True
train_data.loc[train_data['VIP'].isnull() & (train_data['TotalShopping'] == 0), 'VIP'] = False

In [100]:
# To Handle missing values in amenitites 
for ser in amenities:
   train_data[amenities] = train_data[amenities].fillna(0)

In [101]:
train_data.isnull().mean()*100

HomePlanet       0.0
CryoSleep        0.0
Cabin            0.0
Destination      0.0
Age              0.0
VIP              0.0
RoomService      0.0
FoodCourt        0.0
ShoppingMall     0.0
Spa              0.0
VRDeck           0.0
Transported      0.0
Deck             0.0
TotalShopping    0.0
dtype: float64

In [102]:
train_data

,HomePlanet,CryoSleep,Cabin,Destination,Age,VIP,RoomService,FoodCourt,ShoppingMall,Spa,VRDeck,Transported,Deck,TotalShopping
0,Europa,False,B/0/P,TRAPPIST-1e,39.0,False,0.0,0.0,0.0,0.0,0.0,False,B,0.0
1,Earth,False,F/0/S,TRAPPIST-1e,24.0,False,109.0,9.0,25.0,549.0,44.0,True,F,736.0
2,Europa,False,A/0/S,TRAPPIST-1e,58.0,True,43.0,3576.0,0.0,6715.0,49.0,False,A,10383.0
3,Europa,False,A/0/S,TRAPPIST-1e,33.0,False,0.0,1283.0,371.0,3329.0,193.0,False,A,5176.0
4,Earth,False,F/1/S,TRAPPIST-1e,16.0,False,303.0,70.0,151.0,565.0,2.0,True,F,1091.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8688,Europa,False,A/98/P,55 Cancri e,41.0,True,0.0,6819.0,0.0,1643.0,74.0,False,A,8536.0
8689,Earth,True,G/1499/S,PSO J318.5-22,18.0,False,0.0,0.0,0.0,0.0,0.0,False,G,0.0
8690,Earth,False,G/1500/S,TRAPPIST-1e,26.0,False,0.0,0.0,1872.0,1.0,0.0,True,G,1873.0
8691,Europa,False,E/608/S,55 Cancri e,32.0,False,0.0,1049.0,0.0,353.0,3235.0,False,E,4637.0
8692,Europa,False,E/608/S,TRAPPIST-1e,44.0,False,126.0,4688.0,0.0,0.0,12.0,True,E,4826.0

## Converting all string data to int/float

In [103]:
train_data['HomePlanet'].unique()

array(['Europa', 'Earth', 'Mars', 'U'], dtype=object)

In [104]:
# Using Encoder for Homeplanet
train_data = pd.get_dummies(train_data, columns=["HomePlanet"], prefix="HomePlanet", dtype=int)

In [105]:
train_data

,CryoSleep,Cabin,Destination,Age,VIP,RoomService,FoodCourt,ShoppingMall,Spa,VRDeck,Transported,Deck,TotalShopping,HomePlanet_Earth,HomePlanet_Europa,HomePlanet_Mars,HomePlanet_U
0,False,B/0/P,TRAPPIST-1e,39.0,False,0.0,0.0,0.0,0.0,0.0,False,B,0.0,0,1,0,0
1,False,F/0/S,TRAPPIST-1e,24.0,False,109.0,9.0,25.0,549.0,44.0,True,F,736.0,1,0,0,0
2,False,A/0/S,TRAPPIST-1e,58.0,True,43.0,3576.0,0.0,6715.0,49.0,False,A,10383.0,0,1,0,0
3,False,A/0/S,TRAPPIST-1e,33.0,False,0.0,1283.0,371.0,3329.0,193.0,False,A,5176.0,0,1,0,0
4,False,F/1/S,TRAPPIST-1e,16.0,False,303.0,70.0,151.0,565.0,2.0,True,F,1091.0,1,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8688,False,A/98/P,55 Cancri e,41.0,True,0.0,6819.0,0.0,1643.0,74.0,False,A,8536.0,0,1,0,0
8689,True,G/1499/S,PSO J318.5-22,18.0,False,0.0,0.0,0.0,0.0,0.0,False,G,0.0,1,0,0,0
8690,False,G/1500/S,TRAPPIST-1e,26.0,False,0.0,0.0,1872.0,1.0,0.0,True,G,1873.0,1,0,0,0
8691,False,E/608/S,55 Cancri e,32.0,False,0.0,1049.0,0.0,353.0,3235.0,False,E,4637.0,0,1,0,0
8692,False,E/608/S,TRAPPIST-1e,44.0,False,126.0,4688.0,0.0,0.0,12.0,True,E,4826.0,0,1,0,0

In [106]:
## Using ordinal encoder for these cols
cols=['CryoSleep','VIP','Transported']
from sklearn.preprocessing import OrdinalEncoder
for col in cols:
    cat= list(train_data[col].unique())
    ord_enc= OrdinalEncoder(categories=[cat])
    train_data[col]= pd.DataFrame(ord_enc.fit_transform(train_data[[col]]))

In [107]:
train_data

,CryoSleep,Cabin,Destination,Age,VIP,RoomService,FoodCourt,ShoppingMall,Spa,VRDeck,Transported,Deck,TotalShopping,HomePlanet_Earth,HomePlanet_Europa,HomePlanet_Mars,HomePlanet_U
0,0.0,B/0/P,TRAPPIST-1e,39.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,B,0.0,0,1,0,0
1,0.0,F/0/S,TRAPPIST-1e,24.0,0.0,109.0,9.0,25.0,549.0,44.0,1.0,F,736.0,1,0,0,0
2,0.0,A/0/S,TRAPPIST-1e,58.0,1.0,43.0,3576.0,0.0,6715.0,49.0,0.0,A,10383.0,0,1,0,0
3,0.0,A/0/S,TRAPPIST-1e,33.0,0.0,0.0,1283.0,371.0,3329.0,193.0,0.0,A,5176.0,0,1,0,0
4,0.0,F/1/S,TRAPPIST-1e,16.0,0.0,303.0,70.0,151.0,565.0,2.0,1.0,F,1091.0,1,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8688,0.0,A/98/P,55 Cancri e,41.0,1.0,0.0,6819.0,0.0,1643.0,74.0,0.0,A,8536.0,0,1,0,0
8689,1.0,G/1499/S,PSO J318.5-22,18.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,G,0.0,1,0,0,0
8690,0.0,G/1500/S,TRAPPIST-1e,26.0,0.0,0.0,0.0,1872.0,1.0,0.0,1.0,G,1873.0,1,0,0,0
8691,0.0,E/608/S,55 Cancri e,32.0,0.0,0.0,1049.0,0.0,353.0,3235.0,0.0,E,4637.0,0,1,0,0
8692,0.0,E/608/S,TRAPPIST-1e,44.0,0.0,126.0,4688.0,0.0,0.0,12.0,1.0,E,4826.0,0,1,0,0

In [108]:
train_data['Destination'].unique()

array(['TRAPPIST-1e', 'PSO J318.5-22', '55 Cancri e'], dtype=object)

In [109]:
train_data = pd.get_dummies(train_data, columns=['Destination'], prefix='Destination', dtype=int)
train_data

,CryoSleep,Cabin,Age,VIP,RoomService,FoodCourt,ShoppingMall,Spa,VRDeck,Transported,Deck,TotalShopping,HomePlanet_Earth,HomePlanet_Europa,HomePlanet_Mars,HomePlanet_U,Destination_55 Cancri e,Destination_PSO J318.5-22,Destination_TRAPPIST-1e
0,0.0,B/0/P,39.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,B,0.0,0,1,0,0,0,0,1
1,0.0,F/0/S,24.0,0.0,109.0,9.0,25.0,549.0,44.0,1.0,F,736.0,1,0,0,0,0,0,1
2,0.0,A/0/S,58.0,1.0,43.0,3576.0,0.0,6715.0,49.0,0.0,A,10383.0,0,1,0,0,0,0,1
3,0.0,A/0/S,33.0,0.0,0.0,1283.0,371.0,3329.0,193.0,0.0,A,5176.0,0,1,0,0,0,0,1
4,0.0,F/1/S,16.0,0.0,303.0,70.0,151.0,565.0,2.0,1.0,F,1091.0,1,0,0,0,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8688,0.0,A/98/P,41.0,1.0,0.0,6819.0,0.0,1643.0,74.0,0.0,A,8536.0,0,1,0,0,1,0,0
8689,1.0,G/1499/S,18.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,G,0.0,1,0,0,0,0,1,0
8690,0.0,G/1500/S,26.0,0.0,0.0,0.0,1872.0,1.0,0.0,1.0,G,1873.0,1,0,0,0,0,0,1
8691,0.0,E/608/S,32.0,0.0,0.0,1049.0,0.0,353.0,3235.0,0.0,E,4637.0,0,1,0,0,1,0,0
8692,0.0,E/608/S,44.0,0.0,126.0,4688.0,0.0,0.0,12.0,1.0,E,4826.0,0,1,0,0,0,0,1

In [110]:
## For encoding cabin, split it into three parts
train_data[['Deck', 'Num', 'Side']] = train_data['Cabin'].str.split('/', expand=True)
train_data['Num'] = pd.to_numeric(train_data['Num'], errors='coerce')
train_data['Num'] = train_data['Num'].fillna(train_data['Num'].median())

In [111]:
train_data = pd.get_dummies(train_data, columns=['Deck'], prefix='Deck', dtype=int)
train_data['Side'] = train_data['Side'].map({'P': 0, 'S': 1}).fillna(-1).astype(int)
train_data = train_data.drop(columns=['Cabin'])

In [112]:
train_data

,CryoSleep,Age,VIP,RoomService,FoodCourt,ShoppingMall,Spa,VRDeck,Transported,TotalShopping,...,Side,Deck_A,Deck_B,Deck_C,Deck_D,Deck_E,Deck_F,Deck_G,Deck_T,Deck_U
0,0.0,39.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0,0,1,0,0,0,0,0,0,0
1,0.0,24.0,0.0,109.0,9.0,25.0,549.0,44.0,1.0,736.0,...,1,0,0,0,0,0,1,0,0,0
2,0.0,58.0,1.0,43.0,3576.0,0.0,6715.0,49.0,0.0,10383.0,...,1,1,0,0,0,0,0,0,0,0
3,0.0,33.0,0.0,0.0,1283.0,371.0,3329.0,193.0,0.0,5176.0,...,1,1,0,0,0,0,0,0,0,0
4,0.0,16.0,0.0,303.0,70.0,151.0,565.0,2.0,1.0,1091.0,...,1,0,0,0,0,0,1,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8688,0.0,41.0,1.0,0.0,6819.0,0.0,1643.0,74.0,0.0,8536.0,...,0,1,0,0,0,0,0,0,0,0
8689,1.0,18.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1,0,0,0,0,0,0,1,0,0
8690,0.0,26.0,0.0,0.0,0.0,1872.0,1.0,0.0,1.0,1873.0,...,1,0,0,0,0,0,0,1,0,0
8691,0.0,32.0,0.0,0.0,1049.0,0.0,353.0,3235.0,0.0,4637.0,...,1,0,0,0,0,1,0,0,0,0
8692,0.0,44.0,0.0,126.0,4688.0,0.0,0.0,12.0,1.0,4826.0,...,1,0,0,0,0,1,0,0,0,0

## Doing feature scaling do scale down all features

In [113]:
X= train_data.drop(columns = "Transported")
y= train_data["Transported"]

In [114]:
from sklearn.preprocessing import StandardScaler
std_scaler = StandardScaler()
feature_columns = X.columns 
X_scaled = std_scaler.fit_transform(X)
X = pd.DataFrame(X_scaled, columns=feature_columns)

In [115]:
X

,CryoSleep,Age,VIP,RoomService,FoodCourt,ShoppingMall,Spa,VRDeck,TotalShopping,HomePlanet_Earth,...,Side,Deck_A,Deck_B,Deck_C,Deck_D,Deck_E,Deck_F,Deck_G,Deck_T,Deck_U
0,-0.751034,0.711945,-0.191979,-0.333105,-0.281027,-0.283579,-0.270626,-0.263003,-0.514066,-1.060617,...,-0.866174,-0.174191,3.187347,-0.30661,-0.241218,-0.334759,-0.688215,-0.645897,-0.02399,-0.153063
1,-0.751034,-0.334037,-0.191979,-0.168073,-0.275387,-0.241771,0.217158,-0.224205,-0.251479,0.942847,...,0.975267,-0.174191,-0.313741,-0.30661,-0.241218,-0.334759,1.453035,-0.645897,-0.02399,-0.153063
2,-0.751034,2.036857,5.208904,-0.268001,1.959998,-0.283579,5.695623,-0.219796,3.190333,-1.060617,...,0.975267,5.740821,-0.313741,-0.30661,-0.241218,-0.334759,-0.688215,-0.645897,-0.02399,-0.153063
3,-0.751034,0.293552,-0.191979,-0.333105,0.523010,0.336851,2.687176,-0.092818,1.332604,-1.060617,...,0.975267,5.740821,-0.313741,-0.30661,-0.241218,-0.334759,-0.688215,-0.645897,-0.02399,-0.153063
4,-0.751034,-0.891895,-0.191979,0.125652,-0.237159,-0.031059,0.231374,-0.261240,-0.124824,0.942847,...,0.975267,-0.174191,-0.313741,-0.30661,-0.241218,-0.334759,1.453035,-0.645897,-0.02399,-0.153063
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8688,-0.751034,0.851410,5.208904,-0.333105,3.992336,-0.283579,1.189173,-0.197751,2.531369,-1.060617,...,-0.866174,5.740821,-0.313741,-0.30661,-0.241218,-0.334759,-0.688215,-0.645897,-0.02399,-0.153063
8689,1.331498,-0.752431,-0.191979,-0.333105,-0.281027,-0.283579,-0.270626,-0.263003,-0.514066,0.942847,...,0.975267,-0.174191,-0.313741,-0.30661,-0.241218,-0.334759,-0.688215,1.548235,-0.02399,-0.153063
8690,-0.751034,-0.194573,-0.191979,-0.333105,-0.281027,2.846999,-0.269737,-0.263003,0.154175,0.942847,...,0.975267,-0.174191,-0.313741,-0.30661,-0.241218,-0.334759,-0.688215,1.548235,-0.02399,-0.153063
8691,-0.751034,0.223820,-0.191979,-0.333105,0.376365,-0.283579,0.043013,2.589576,1.140302,-1.060617,...,0.975267,-0.174191,-0.313741,-0.30661,-0.241218,2.987225,-0.688215,-0.645897,-0.02399,-0.153063
8692,-0.751034,1.060606,-0.191979,-0.142335,2.656871,-0.283579,-0.270626,-0.252422,1.207732,-1.060617,...,0.975267,-0.174191,-0.313741,-0.30661,-0.241218,2.987225,-0.688215,-0.645897,-0.02399,-0.153063

## Doing Same things on test_data

In [116]:
# 1. Deck Extraction & Missing Values Handling
test_data["Cabin"] = test_data["Cabin"].fillna("U")
test_data["Deck"] = test_data["Cabin"].apply(lambda x: x[0])

# 2. Total Amenities & CryoSleep Imputation
amenities = ["RoomService", "FoodCourt", "ShoppingMall", "Spa", "VRDeck"]
test_data["TotalShopping"] = test_data[amenities].sum(axis=1)

test_data.loc[test_data["CryoSleep"].isnull() & (test_data["TotalShopping"] > 0),"CryoSleep",] = False
test_data.loc[test_data["CryoSleep"].isnull() & (test_data["TotalShopping"] == 0),"CryoSleep",] = True

# Zero out amenities for passengers in CryoSleep
for col in amenities:
  test_data.loc[test_data["CryoSleep"] == True, col] = test_data[col].fillna(0)

# 3. Impute Destination with train_data mode
test_data["Destination"] = test_data["Destination"].fillna(destination_mode)

# 4. Impute Age using fitted SimpleImputer
test_data["Age"] = sim_imp.transform(test_data[["Age"]])

# 5. Impute VIP based on spending
test_data.loc[test_data["VIP"].isnull() & (test_data["TotalShopping"] > 0), "VIP"] = True
test_data.loc[test_data["VIP"].isnull() & (test_data["TotalShopping"] == 0), "VIP"] = False

# Fill remaining missing amenity values with 0
test_data[amenities] = test_data[amenities].fillna(0)

# Fill missing HomePlanet values with 'U' if not already done
test_data["HomePlanet"] = test_data["HomePlanet"].fillna("U")

# 6. One-Hot Encoding for HomePlanet
test_data = pd.get_dummies(
    test_data, columns=["HomePlanet"], prefix="HomePlanet", dtype=int
)

# Align columns in case a category was missing in test set
test_data = test_data.reindex(
    columns=[c for c in train_data.columns if c != "Transported"], fill_value=0
)

# 7. Encode Boolean Columns
cols_to_encode = ["CryoSleep", "VIP"]
for col in cols_to_encode:
  test_data[col] = test_data[col].astype(int)
    
# 8. Align columns to match X's exact structure before scaling
test_data = test_data.reindex(columns=feature_columns, fill_value=0)

# 9. Apply the fitted StandardScaler from Cell 30
X_test_scaled = std_scaler.transform(test_data)
test = pd.DataFrame(X_test_scaled, columns=feature_columns)

In [117]:
test

,CryoSleep,Age,VIP,RoomService,FoodCourt,ShoppingMall,Spa,VRDeck,TotalShopping,HomePlanet_Earth,...,Side,Deck_A,Deck_B,Deck_C,Deck_D,Deck_E,Deck_F,Deck_G,Deck_T,Deck_U
0,1.331498,-0.124841,-0.191979,-0.333105,-0.281027,-0.283579,-0.270626,-0.263003,-0.514066,0.942847,...,-0.866174,-0.174191,-0.313741,-0.30661,-0.241218,-0.334759,-0.688215,-0.645897,-0.02399,-0.153063
1,-0.751034,-0.682698,-0.191979,-0.333105,-0.275387,-0.283579,2.237598,-0.263003,0.496322,0.942847,...,-0.866174,-0.174191,-0.313741,-0.30661,-0.241218,-0.334759,-0.688215,-0.645897,-0.02399,-0.153063
2,1.331498,0.154088,-0.191979,-0.333105,-0.281027,-0.283579,-0.270626,-0.263003,-0.514066,-1.060617,...,-0.866174,-0.174191,-0.313741,-0.30661,-0.241218,-0.334759,-0.688215,-0.645897,-0.02399,-0.153063
3,-0.751034,0.642213,-0.191979,-0.333105,3.887680,-0.283579,-0.109808,0.252842,2.132494,-1.060617,...,-0.866174,-0.174191,-0.313741,-0.30661,-0.241218,-0.334759,-0.688215,-0.645897,-0.02399,-0.153063
4,-0.751034,-0.612966,-0.191979,-0.317964,-0.281027,0.778343,-0.270626,-0.263003,-0.283945,0.942847,...,-0.866174,-0.174191,-0.313741,-0.30661,-0.241218,-0.334759,-0.688215,-0.645897,-0.02399,-0.153063
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4272,1.331498,0.363284,-0.191979,-0.333105,-0.281027,-0.283579,-0.270626,-0.263003,-0.514066,0.942847,...,-0.866174,-0.174191,-0.313741,-0.30661,-0.241218,-0.334759,-0.688215,-0.645897,-0.02399,-0.153063
4273,-0.751034,0.921142,-0.191979,-0.333105,0.249775,-0.255149,-0.261741,-0.136026,-0.150868,0.942847,...,-0.866174,-0.174191,-0.313741,-0.30661,-0.241218,-0.334759,-0.688215,-0.645897,-0.02399,-0.153063
4274,1.331498,-0.124841,-0.191979,-0.333105,-0.281027,-0.283579,-0.270626,-0.263003,-0.514066,-1.060617,...,-0.866174,-0.174191,-0.313741,-0.30661,-0.241218,-0.334759,-0.688215,-0.645897,-0.02399,-0.153063
4275,-0.751034,-0.124841,-0.191979,-0.333105,1.398488,-0.283579,-0.270626,0.198171,0.628686,-1.060617,...,-0.866174,-0.174191,-0.313741,-0.30661,-0.241218,-0.334759,-0.688215,-0.645897,-0.02399,-0.153063
4276,1.331498,0.990874,-0.191979,-0.333105,-0.281027,-0.283579,-0.270626,-0.263003,-0.514066,0.942847,...,-0.866174,-0.174191,-0.313741,-0.30661,-0.241218,-0.334759,-0.688215,-0.645897,-0.02399,-0.153063

## Choosing and Training of model

In [118]:
## Train test split
from sklearn.model_selection import train_test_split
X_train, X_test, y_train,y_test= train_test_split(X,y, random_state=42, test_size=0.2)

In [119]:
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier, AdaBoostClassifier
import xgboost as xgb
import lightgbm as lgb
from sklearn.model_selection import cross_val_score

models = {
    'lr': LogisticRegression(),
    'svm': SVC(),
    'dtree': DecisionTreeClassifier(),
    'rf': RandomForestClassifier(n_estimators=50),
    'xg': xgb.XGBClassifier(n_estimators=100),
    'gb': GradientBoostingClassifier(),
    'adb': AdaBoostClassifier(),
    'lgbm': lgb.LGBMClassifier()
}

for name, model in models.items():
    scores = cross_val_score(model, X_train, y_train, cv=5)
    print(f"{name} accuracy: {scores.mean() * 100:.2f}%")

lr accuracy: 79.26%
svm accuracy: 80.37%
dtree accuracy: 75.09%
rf accuracy: 79.90%
xg accuracy: 80.72%
gb accuracy: 80.86%
adb accuracy: 78.19%
[LightGBM] [Warning] Found whitespace in feature_names, replace with underlines
[LightGBM] [Info] Number of positive: 2800, number of negative: 2763
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.000762 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 1919
[LightGBM] [Info] Number of data points in the train set: 5563, number of used features: 26
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.503326 -> initscore=0.013302
[LightGBM] [Info] Start training from score 0.013302
[LightGBM] [Warning] Found whitespace in feature_names, replace with underlines
[LightGBM] [Info] Number of positive: 2800, number of negative: 2763
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.000670 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 1917
[LightGBM] [Info] Number of data points in the train set: 5563, number of used features: 26
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.503326 -> initscore=0.013302
[LightGBM] [Info] Start training from score 0.013302
[LightGBM] [Warning] Found whitespace in feature_names, replace with underlines
[LightGBM] [Info] Number of positive: 2800, number of negative: 2763
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.000767 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 1918
[LightGBM] [Info] Number of data points in the train set: 5563, number of used features: 26
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.503326 -> initscore=0.013302
[LightGBM] [Info] Start training from score 0.013302
[LightGBM] [Warning] Found whitespace in feature_names, replace with underlines
[LightGBM] [Info] Number of positive: 2800, number of negative: 2763
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.000759 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 1917
[LightGBM] [Info] Number of data points in the train set: 5563, number of used features: 26
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.503326 -> initscore=0.013302
[LightGBM] [Info] Start training from score 0.013302
[LightGBM] [Warning] Found whitespace in feature_names, replace with underlines
[LightGBM] [Info] Number of positive: 2800, number of negative: 2764
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.000791 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 1918
[LightGBM] [Info] Number of data points in the train set: 5564, number of used features: 26
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.503235 -> initscore=0.012941
[LightGBM] [Info] Start training from score 0.012941
lgbm accuracy: 81.20%

In [120]:
## Doing hyperparamter tuning for lightgbm
from lightgbm import LGBMClassifier
from sklearn.model_selection import RandomizedSearchCV
param_distributions = {
    'n_estimators': [50, 100, 200, 500],
    'learning_rate': [0.01, 0.05, 0.1, 0.2],
    'num_leaves': [15, 31, 50, 63],
    'max_depth': [-1, 5, 10, 15],
    'subsample': [0.6, 0.8, 1.0],
    'colsample_bytree': [0.6, 0.8, 1.0],
    'min_child_samples': [10, 20, 30]
}
lgb_model = LGBMClassifier(random_state=42)

random_search = RandomizedSearchCV(
    estimator=lgb_model,
    param_distributions=param_distributions,
    n_iter=20,       
    cv=5,              
    scoring='accuracy',
    random_state=42,
    n_jobs=-1,          
    verbose=1
)

random_search.fit(X_train, y_train)

print(f"Best Accuracy: {random_search.best_score_ * 100:.2f}%")
print("Best Parameters:")
print(random_search.best_params_)

best_lgb = random_search.best_estimator_

Fitting 5 folds for each of 20 candidates, totalling 100 fits
[LightGBM] [Warning] Found whitespace in feature_names, replace with underlines
[LightGBM] [Info] Number of positive: 2800, number of negative: 2763
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.000836 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 1917
[LightGBM] [Info] Number of data points in the train set: 5563, number of used features: 26
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.503326 -> initscore=0.013302
[LightGBM] [Info] Start training from score 0.013302
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf[LightGBM] [Warning] Found whitespace in feature_names, replace with underlines
[LightGBM] [Info] Number of positive: 2800, number of negative: 2763
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.015475 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 1918
[LightGBM] [Info] Number of data points in the train set: 5563, number of used features: 26
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.503326 -> initscore=0.013302
[LightGBM] [Info] Start training from score 0.013302
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf[LightGBM] [Warning] Found whitespace in feature_names, replace with underlines
[LightGBM] [Info] Number of positive: 2800, number of negative: 2763
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.000929 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 1919
[LightGBM] [Info] Number of data points in the train set: 5563, number of used features: 26
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.503326 -> initscore=0.013302
[LightGBM] [Info] Start training from score 0.013302
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf

In [121]:
import lightgbm as lgb
lgb_model = lgb.LGBMClassifier(
    subsample=0.8,
    num_leaves=15,
    n_estimators=15,
    learning_rate=0.1,
    colsample_bytree=1.0,
    random_state=42
)
lgb_model.fit(X_train, y_train)

[LightGBM] [Warning] Found whitespace in feature_names, replace with underlines
[LightGBM] [Info] Number of positive: 3500, number of negative: 3454
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.001277 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 1919
[LightGBM] [Info] Number of data points in the train set: 6954, number of used features: 26
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.503307 -> initscore=0.013230
[LightGBM] [Info] Start training from score 0.013230

LGBMClassifier(n_estimators=15, num_leaves=15, random_state=42, subsample=0.8)

In [122]:
lgb_model.score(X_test,y_test)

0.7883841288096607

In [123]:

original_test = pd.read_csv("/kaggle/input/competitions/spaceship-titanic/test.csv")

test_features = test_data.drop(columns=['Cabin'], errors='ignore')

predictions = lgb_model.predict(test_features)

submission = pd.DataFrame({
    'PassengerId': original_test['PassengerId'],
    'Transported': predictions.astype(bool)
})

submission.to_csv("submission.csv", index=False)
submission.head()

  PassengerId  Transported
0     0013_01         True
1     0018_01        False
2     0019_01         True
3     0021_01        False
4     0023_01        False